services:
  - name: web
    type: web_service
    env: python
    buildCommand: python3 -m pip install -r requirements.txt
    startCommand: gunicorn main:app -b :$PORT --timeout 2400 --workers 200 --threads 16
    plan: team
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
