services:
- type: web
  name: ernierank-vd20
  env: python
  plan: performance
  buildCommand: pip3 install -r requirements.txt
  startCommand: gunicorn -w 16 -k gevent -t 120 main:app -b :$PORT
  envVars:
    - key: FLASK_APP
      value: main.py
    - key: FLASK_ENV
      value: production
    - key: WORKERS
      value: 16
    - key: WORKER_CLASS
      value: gevent
    - key: TIMEOUT
      value: 120
